Portfolio : Add Details Popup Window
OmarRamoun/clean-blue pull request #19
Opened 2021-09-04 17:20 UTC by MrRamoun

## Enhancement Needed :recycle: 

- :heavy_plus_sign: Update the main page so that the projects section is created dynamically using js.
- :heavy_plus_sign: Add Layout & Style to the details popup window.
- :heavy_plus_sign: Add the popup window js script to be added dynamically to the page.
- :heavy_plus_sign: Add toggles for the close button to close the popup window.

2021-09-04 17:39 UTC, mke2111 requested changes
### Hey @MrRamoun,

**This is a great project you have going on, well-done lad**. 
   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-04 17:43 UTC, mke2111 commented on js/load.js
> +      link: '#',
- [ ] For this milestone, you are required to have all your projects in an array of objects. Each object should contain details of a project.

2021-09-05 00:47 UTC, carlos-ssh requested changes
Hi @MrRamoun , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-05 00:47 UTC, carlos-ssh commented on js/load.js
> +const works = [work1, work2, work3, work4];
Kindly make these requited changes:
- In order to associate each project with the popup window details, you must use a JavaScript array to store all of the information for all projects.
- For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.

Kindly store your ` const ` inside of an ` array `:

```
const projects = [
 {
    name: "Submarine game",
    description: "A Phaser3 plataformer game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
 },
  {  name: "Submarine game",
    description: "A Phaser3 plataformer game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
   }
]

```

**_The JavaScript code implements an array of objects to store JavaScript objects containing the information for each project._**

I hope that this information will be helpful for you.

2021-09-05 01:30 UTC, carlos-ssh approved these changes
Hi @MrRamoun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-05 01:31 UTC, merged